#!/bin/sh

case $# in
  0)
    # TODO go up the hierarchy to find .ship
    source .ship

    COMMANDS="cd $DESTINATION;"

    if [ -n "$BEFORE" ]; then
        COMMANDS="$COMMANDS $BEFORE;"
    fi

    COMMANDS="$COMMANDS git pull origin master;"
    COMMANDS="$COMMANDS [ -e composer.json ] && composer install;"
    COMMANDS="$COMMANDS [ -e package.json ] && npm install;"

    if [ -n "$AFTER" ]; then
        COMMANDS="$COMMANDS $AFTER;"
    fi

    ssh $USERNAME@$SERVER "$COMMANDS"
    ;;

  4)
    if [ "$1" == "init" ]; then
      USERNAME=$2
      SERVER=$3
      DESTINATION=$4
      CLONEURL=`git config --get remote.origin.url`

      ssh captain@$SERVER "
        if [ -a $DESTINATION ]; then
          echo "Error: Destination exists"
          exit 1
        else
          git clone $CLONEURL $DESTINATION
        fi
      "

      if [ $? -eq 0 ]; then
        echo "USERNAME=$USERNAME"       >  .ship
        echo "SERVER=$SERVER"           >> .ship
        echo "DESTINATION=$DESTINATION" >> .ship
      fi
    else
      echo "Error: Invalid argument '$1'"
    fi
    ;;

  *)
    echo "Usage: ship [init username server destination]"
    exit 1
    ;;
esac
