#!/bin/sh

case $# in
  0)
    while [[ "$PWD" != "/" ]]
    do
      if [[ -e ".ship" ]]
      then
        source .ship
        break
      fi

      cd ..
    done

    if [[ -n "$USER" && -n "$SERVER" && -n "DESTINATION" ]]
    then
      COMMANDS="cd $DESTINATION;"

      if [ -n "$BEFORE" ]
      then
        COMMANDS="$COMMANDS $BEFORE;"
      fi

      COMMANDS="$COMMANDS git pull origin master;"
      COMMANDS="$COMMANDS [ -e composer.json ] && composer install;"
      COMMANDS="$COMMANDS [ -e package.json ] && npm install;"

      if [ -n "$AFTER" ]
      then
        COMMANDS="$COMMANDS $AFTER;"
      fi

      ssh $USER@$SERVER "$COMMANDS"
    else
      if [[ -e ".ship" ]]
      then
        if [ -z "$USER" ]
        then
          MISSING="USER"
        elif [ -z "$SERVER" ]
        then
          MISSING="SERVER"
        elif [ -z "$DESTINATION" ]
        then
          MISSING="DESTINATION"
        fi

        echo "Error: .ship found, but is missing $MISSING."
      else
        echo "Error: Unable to locate .ship"
      fi

      exit 1
    fi
    ;;

  4)
    if [ "$1" == "init" ]
    then
      USER=$2
      SERVER=$3
      DESTINATION=$4
      CLONEURL=`git config --get remote.origin.url`

      ssh captain@$SERVER "
        if [ -a $DESTINATION ]; then
          echo "Error: Destination exists"
          exit 1
        else
          git clone $CLONEURL $DESTINATION
        fi
      "

      if [ $? -eq 0 ]
      then
        echo "USER=$USER"       >  .ship
        echo "SERVER=$SERVER"           >> .ship
        echo "DESTINATION=$DESTINATION" >> .ship
      fi
    else
      echo "Error: Invalid argument '$1'"
    fi
    ;;

  *)
    echo "Usage: ship [init user server destination]"
    exit 1
    ;;
esac
